import { BRAND, BrandPdf } from "./pdf-brand";

export type CommandReportSection = {
  heading: string;
  lines: string[];
  /** Optional chart rendered under the section's bullets. */
  chart?: { title: string; rows: { label: string; value: number }[]; suffix?: string };
  /** Optional headline tiles for the section. */
  stats?: { label: string; value: string; tone?: "red" | "green" | "ink" }[];
  /** Optional highlighted read for the section. */
  callout?: { title: string; body: string; tone?: "red" | "green" | "amber" };
};

/** Branded export used by the crisis room, daily brief and campaign proof. */
export async function downloadCommandReportPdf(input: {
  title: string;
  subtitle?: string;
  filename: string;
  generatedAt?: string | null;
  sections: CommandReportSection[];
}) {
  const pdf = new BrandPdf();

  await pdf.cover({
    title: input.title,
    subtitle: input.subtitle,
    generatedAt: input.generatedAt ?? null,
  });

  for (const section of input.sections) {
    pdf.heading(section.heading);
    if (section.stats?.length) pdf.statCards(section.stats);
    if (section.callout) {
      pdf.callout(section.callout.title, section.callout.body, section.callout.tone ?? "green");
    }
    for (const line of section.lines.filter(Boolean)) pdf.bullet(line);
    if (section.chart?.rows.length) {
      pdf.barChart(section.chart.title, section.chart.rows, { suffix: section.chart.suffix ?? "" });
    }
  }

  pdf.note("Generated by FKF CommsIQ from the records stored at the time of export.");
  pdf.save(input.filename);
  return BRAND;
}
