/**
 * Rough gender read for audience demographics.
 * X profiles carry no gender field, so we infer from the display name using
 * common Kenyan and international given names. Anything we can't place stays
 * "unknown" — the UI shows it as such rather than guessing.
 */

export type GenderGuess = "female" | "male" | "unknown";

const FEMALE = new Set([
  "mary",
  "grace",
  "faith",
  "joyce",
  "esther",
  "jane",
  "lucy",
  "ann",
  "anne",
  "annie",
  "nancy",
  "susan",
  "rose",
  "roseline",
  "caroline",
  "carolyne",
  "mercy",
  "purity",
  "beatrice",
  "eunice",
  "winnie",
  "wanjiru",
  "wanjiku",
  "njeri",
  "nyambura",
  "wairimu",
  "akinyi",
  "atieno",
  "adhiambo",
  "anyango",
  "auma",
  "chebet",
  "jepkorir",
  "jerop",
  "cherono",
  "naliaka",
  "nekesa",
  "amina",
  "halima",
  "fatuma",
  "zainab",
  "aisha",
  "khadija",
  "sarah",
  "sara",
  "ruth",
  "rebecca",
  "elizabeth",
  "emily",
  "catherine",
  "cathy",
  "christine",
  "diana",
  "doris",
  "florence",
  "gladys",
  "hellen",
  "helen",
  "irene",
  "janet",
  "joan",
  "judy",
  "julia",
  "juliet",
  "linda",
  "lilian",
  "maureen",
  "millicent",
  "monica",
  "nelly",
  "pauline",
  "phoebe",
  "rachael",
  "rachel",
  "sharon",
  "sheila",
  "shiro",
  "stella",
  "teresa",
  "valentine",
  "veronica",
  "vivian",
  "wangari",
  "waithera",
  "kemunto",
  "nyaboke",
  "moraa",
  "kerubo",
  "bochere",
  "sylvia",
  "sylvie",
  "brenda",
  "cynthia",
  "emma",
  "hannah",
  "laura",
  "megan",
  "olivia",
  "sophia",
  "sophie",
  "victoria",
  "zawadi",
]);

const MALE = new Set([
  "john",
  "peter",
  "james",
  "david",
  "daniel",
  "samuel",
  "joseph",
  "paul",
  "george",
  "kevin",
  "brian",
  "collins",
  "dennis",
  "eric",
  "felix",
  "francis",
  "geoffrey",
  "gideon",
  "isaac",
  "jackson",
  "kelvin",
  "kennedy",
  "martin",
  "michael",
  "moses",
  "nicholas",
  "patrick",
  "philip",
  "richard",
  "robert",
  "simon",
  "stephen",
  "steve",
  "thomas",
  "victor",
  "vincent",
  "willis",
  "william",
  "hussein",
  "mohamed",
  "mohammed",
  "muhammad",
  "abdi",
  "abdul",
  "ali",
  "omar",
  "yusuf",
  "hassan",
  "salim",
  "said",
  "kamau",
  "kariuki",
  "mwangi",
  "njoroge",
  "githinji",
  "otieno",
  "ochieng",
  "odhiambo",
  "omondi",
  "owino",
  "onyango",
  "okoth",
  "kipchoge",
  "kipruto",
  "kiptoo",
  "kibet",
  "kiprop",
  "rotich",
  "cheruiyot",
  "wafula",
  "wanyama",
  "barasa",
  "juma",
  "mutua",
  "mutiso",
  "musyoka",
  "kioko",
  "mwendwa",
  "kilonzo",
  "andrew",
  "anthony",
  "antony",
  "benjamin",
  "charles",
  "chris",
  "christopher",
  "edwin",
  "elijah",
  "emmanuel",
  "evans",
  "fredrick",
  "frederick",
  "henry",
  "ian",
  "jacob",
  "jeremiah",
  "joshua",
  "julius",
  "leonard",
  "mark",
  "nelson",
  "oscar",
  "raphael",
  "ronald",
  "shadrack",
  "timothy",
  "tony",
  "tom",
]);

/** Strips emoji, punctuation and honorifics, then matches the first two tokens. */
export function guessGender(displayName: string): GenderGuess {
  const cleaned = displayName
    .toLowerCase()
    .replace(/[^a-z\s'-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  if (!cleaned) return "unknown";

  const tokens = cleaned.split(" ").filter((t) => t.length > 2);
  for (const token of tokens.slice(0, 3)) {
    if (token === "mr" || token === "sir") return "male";
    if (token === "mrs" || token === "ms" || token === "miss") return "female";
    if (FEMALE.has(token)) return "female";
    if (MALE.has(token)) return "male";
  }
  return "unknown";
}
