export type Persona = {
  id: string;
  name: string;
  segment: string;
  role: string;
  age: number;
  location: string;
  vibe: string;
  quote: string;
  decisionStyle: string;
  platforms: string[];
  traits: Record<string, number>;
  profile: string;
};

/**
 * 100 synthetic, research-calibrated personas extracted from the
 * "Urban Kenya Persona Profiles" deck (Big Five, Hofstede cultural
 * dimensions and Nairobi digital-behaviour research).
 */
export const PERSONAS: Persona[] = [
  {
    id: "amara-achieng",
    name: "Amara Achieng",
    segment: "Urban Tech Designer & Queer Advocate",
    role: "UX/UI Designer & Tech Blogger",
    age: 27,
    location: "Kilimani",
    vibe: "Bold tech queer",
    quote: "UX Designer by day. Queer by nature. Coffee addict. Nairobi.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Tech affinity": 95 },
    profile:
      "Amara values design precision, authenticity, and LGBTQ+ safety. She responds to direct, transparent, and bold messaging. Fluff, pandering, and hostility turn her off completely. She frequents Instagram, X, LinkedIn, and Pinterest for design news. Highly price-insensitive for high-quality, high-utility tech tools and lifestyle items.",
  },
  {
    id: "zawadi-mwangi",
    name: "Zawadi Mwangi",
    segment: "Trendsetting Urban Fashion Stylist",
    role: "Fashion Stylist & Personal Shopper",
    age: 25,
    location: "Westlands",
    vibe: "Glamorous, extra",
    quote: "Fashion stylist. Personal shopper. Nairobi's best-dressed problem.",
    decisionStyle: "Spontaneous, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Tech affinity": 72 },
    profile:
      "Zawadi values status, peer recommendations, and visual aesthetics. She loves playful, trendy, and social-proof-heavy messaging that highlights exclusivity. Corporate jargon and cold sales pitches turn her off instantly. She relies heavily on Instagram, TikTok, and WhatsApp. Moderately price-sensitive, balancing thrifty value with premium statement investments.",
  },
  {
    id: "kendi-muthoni",
    name: "Kendi Muthoni",
    segment: "Mindful Urban Health Practitioner",
    role: "Clinical Psychologist & Mental Health Advocate",
    age: 30,
    location: "Lavington",
    vibe: "Calm healer",
    quote:
      "Clinical Psychologist. Mental health advocate. Protecting my peace, healing others. Nairobi.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["Instagram", "WhatsApp", "Twitter / X"],
    traits: { "Tech affinity": 55 },
    profile:
      "Kendi values mental wellness, authentic peace, and cultural balance. Calm, empathetic, and evidence-backed messages win her over easily. Hype, aggressive sales tactics, and superficial self-care claims turn her off. She uses digital channels sparingly in mornings/evenings, prioritizing offline mindfulness. Moderately price-sensitive, investing purposefully in personal wellbeing.",
  },
  {
    id: "chidi-omondi",
    name: "Chidi Omondi",
    segment: "Charismatic Culinary Artist & Chef",
    role: "Culinary Artist / Private Chef",
    age: 28,
    location: "South B",
    vibe: "Charismatic foodie",
    quote: "Culinary artist. Private chef. I'll feed your soul and your stomach. Nairobi.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Tech affinity": 58 },
    profile:
      "Chidi values authentic local roots, culinary craft, and storytelling. Warm, storytelling-driven, and culturally grounded messages win him over. Pretentiousness and overly processed ideas turn him off fast. He browses media during relaxed evenings, focusing on Instagram visuals. Moderate price sensitivity, prioritizing fresh, high-quality, local produce over brands.",
  },
  {
    id: "taji-kariuki",
    name: "Taji Kariuki",
    segment: "Laidback Independent Music Producer",
    role: "Music Producer & DJ",
    age: 26,
    location: "Kilimani",
    vibe: "Cool, laidback DJ",
    quote: "Music producer. DJ. Vibes curator. Nairobi's sound shaper.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Tech affinity": 86 },
    profile:
      "Taji values creative freedom, authenticity, and precision. Subtle, respectful, and artist-centric messaging resonates with him deeply. Micro-management, forced trends, and rigid demands turn him off immediately. He consumes media late at night across music platforms. Price-insensitive for premium audio equipment, but frugal on casual consumer goods.",
  },
  {
    id: "david-kiplagat",
    name: "David Kiplagat",
    segment: "Diaspora Cloud Tech Engineer",
    role: "Senior Software Engineer, Cloud Infrastructure",
    age: 29,
    location: "Eldoret, Kenya",
    vibe: "Quiet overachiever",
    quote:
      "Left Eldoret on a CS scholarship. Never planned to stay this long. Still sends more of his paycheck home than he tells his American friends.",
    decisionStyle: "Analytical, Independent",
    platforms: ["LinkedIn", "Twitter / X", "WhatsApp", "YouTube"],
    traits: { "Tech affinity": 92 },
    profile:
      "David values financial security, efficiency, and supporting family back home. Pragmatic, data-driven, and value-oriented messages win him over. Excessive luxury marketing and unproven claims turn him off completely. He frequents tech WhatsApp groups and professional networks. Highly price-conscious, prioritizing savings, remittances, and long-term investments.",
  },
  {
    id: "faith-wanjiru",
    name: "Faith Wanjiru",
    segment: "Dedicated Diaspora Healthcare Professional",
    role: "Senior Staff Nurse, NHS Elderly Care Ward",
    age: 41,
    location: "Nyeri, Kenya (UK diaspora)",
    vibe: "Steady backbone",
    quote: "Sixteen years in the NHS. Raised two kids on two continents. Still calls Nyeri home.",
    decisionStyle: "Cautious, Family-led",
    platforms: ["WhatsApp", "Facebook", "YouTube"],
    traits: { "Tech affinity": 45 },
    profile:
      "Faith values family welfare, hard work, and long-term stability. Respectful, clear, and trust-building messages resonate strongly with her. Hidden fees, flashy gimmicks, and unreliable services turn her off instantly. She checks media between demanding shifts, mostly using WhatsApp. High price sensitivity, carefully managing funds for family remittances and retirement.",
  },
  {
    id: "amina-hassan",
    name: "Amina Hassan",
    segment: "Resilient Migrant Household Worker",
    role: "Domestic Worker / Household Manager",
    age: 34,
    location: "Mombasa, Kenya (Gulf diaspora)",
    vibe: "Resilient provider",
    quote:
      "Left Mombasa for a two-year contract. That was six years ago. Every shilling has a job before it even arrives.",
    decisionStyle: "Cautious, Family-led",
    platforms: ["WhatsApp", "TikTok", "Facebook"],
    traits: { "Tech affinity": 50 },
    profile:
      "Amina values family security, thriftiness, and reliability. Direct, reassuring, and family-focused messages win her trust. Vague terms, wasteful promises, and complex conditions turn her off completely. She uses phone media briefly late at night, favoring WhatsApp voice notes. Extremely price-sensitive, allocating every unit of currency toward home support.",
  },
  {
    id: "elijah-kiptoo",
    name: "Elijah Kiptoo",
    segment: "Disciplined International Elite Athlete",
    role: "Professional Marathon Runner",
    age: 24,
    location: "Iten, Kenya",
    vibe: "Disciplined dreamer",
    quote:
      "Grew up running to school in Iten. Now runs for a Dutch management group and a plane ticket home twice a year.",
    decisionStyle: "Disciplined, Advisor-led",
    platforms: ["Instagram", "WhatsApp", "Twitter / X"],
    traits: { "Tech affinity": 60 },
    profile:
      "Elijah values discipline, physical performance, and financial growth. Simple, performance-focused, and supportive messages win him over. Distractions, flashy hype, and overly complex offers turn him off. He checks media mid-morning between grueling training sessions. Highly price-sensitive, treating income as temporary while sending most earnings to family.",
  },
  {
    id: "abdirahman-yusuf",
    name: "Abdirahman Yusuf",
    segment: "Established Eastleigh Wholesale Trader",
    role: "Wholesale Trader - Textiles & Electronics Import",
    age: 45,
    location: "Mogadishu, Somalia",
    vibe: "Self-made trader",
    quote:
      "Arrived in Eastleigh with nothing in the '90s. Now runs three shops and half a building.",
    decisionStyle: "Fast, Network-led",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Tech affinity": 55 },
    profile:
      "Abdirahman values trust, kin networks, and legacy building. Straightforward, honor-based, and deal-focused messages win him over. Unnecessary bureaucracy, disrespect, and empty promises turn him off immediately. He uses messaging tools constantly throughout the day for business. Value-driven and pragmatic, highly price-sensitive to transaction margins but willing to invest heavily in family.",
  },
  {
    id: "min-zhang",
    name: "Min Zhang",
    segment: "Pragmatic Chinese B2B Business Owner",
    role: "Import-Export Business Owner - Hardware & Construction Materials",
    age: 38,
    location: "Yiwu, China",
    vibe: "Pragmatic builder",
    quote:
      "Came to Nairobi to open one container's worth of stock. Eleven years later, she runs a warehouse and a small assembly line.",
    decisionStyle: "Pragmatic, Independent",
    platforms: ["WeChat", "WhatsApp", "LinkedIn"],
    traits: { "Tech affinity": 65 },
    profile:
      "Values pragmatic reliability, fair dealing, and business continuity. Pragmatic, respectful, and direct messaging wins her over. Political noise, xenophobic tropes, or overly complex promises turn her off. She consumes WeChat and industry channels; tech-savvy but practical. Moderately price-sensitive, balancing cost with product durability and supplier trustworthiness.",
  },
  {
    id: "charlotte-whitfield",
    name: "Charlotte Whitfield",
    segment: "Impact Minded International NGO Manager",
    role: "Programme Manager, International NGO (Climate & Livelihoods)",
    age: 31,
    location: "Bristol, UK",
    vibe: "Earnest idealist",
    quote:
      "Came for a two-year contract. Four years later, still here, still arguing with herself about what that means.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Tech affinity": 75 },
    profile:
      "Values ethical impact, sustainability, and authentic community engagement. Earnest, reflective, and evidence- backed messaging wins her over. Preachy self-righteousness or superficial virtue signaling turns her off. Reached via social platforms during relaxed evenings. High price sensitivity around value alignment, but possesses generous disposable income for ethics-driven purchases.",
  },
  {
    id: "kiran-shah",
    name: "Kiran Shah",
    segment: "Heritage Family Hardware Business Owner",
    role: "Third-Generation Business Owner - Hardware & Industrial Supplies",
    age: 58,
    location: "Nairobi, Kenya",
    vibe: "Heritage Family",
    quote:
      "His grandfather laid track for the railway. His father built the shop. He's still arguing with his kids about whether they'll keep it.",
    decisionStyle: "Deliberate, Relationship-led",
    platforms: ["WhatsApp", "Facebook"],
    traits: { "Tech affinity": 40 },
    profile:
      "Values deep personal relationships, legacy, and proven reliability. Respectful, tradition-honoring, and loyalty-focused messaging wins him over. Rapid, disruptive sales pitches or disrespect toward established ways turn him off. Reached mainly via WhatsApp family and business chats. High price sensitivity regarding margins, prioritizing long-term trust over cheap trends.",
  },
  {
    id: "elmarie-van-der-merwe",
    name: "Elmarie van der Merwe",
    segment: "Faith and Family Suburban Homemaker",
    role: "Homemaker & Community Volunteer",
    age: 54,
    location: "South Africa",
    vibe: "Warm homebody",
    quote: "Ma van twee. Coffee, rugby, and a garden that keeps me honest.",
    decisionStyle: "Cautious, Loyalty-led",
    platforms: ["Facebook", "WhatsApp", "Twitter / X"],
    traits: { "Tech affinity": 30, "Brand loyalty": 75 },
    profile:
      "Values family, faith, community care, and practical everyday warmth. Friendly, sincere, and wholesome messaging wins her over. Flashy, overly technical, or cynical tones turn her off. Reached slowly on personal X feeds and quiet morning browsing. Price-sensitive and budget-conscious, staying highly loyal to familiar, dependable brands once won over.",
  },
  {
    id: "akoth-otieno",
    name: "Akoth Otieno",
    segment: "Mindful Urban Marketing Young Professional",
    role: "Marketing Coordinator",
    age: 26,
    location: "Nairobi, Kenya",
    vibe: "Mindful Urban",
    quote: "Trying to life one cup of coffee at a time.",
    decisionStyle: "Deliberate, Peer-informed",
    platforms: ["Instagram", "Twitter / X", "WhatsApp"],
    traits: { "Tech affinity": 70, "Brand loyalty": 45 },
    profile:
      "Values mental balance, quiet self-improvement, and authentic everyday rituals. Calm, aesthetic, and low-pressure messaging wins her over. Aggressive hustle-culture language and loud sales pitches turn her off. Active on Instagram and X during early mornings. Price-conscious yet willing to spend on meaningful self-care and micro-indulgences.",
  },
  {
    id: "zuri",
    name: "Zuri",
    segment: "Family Centric Urban Customer Associate",
    role: "Customer Success Associate",
    age: 29,
    location: "Kenya",
    vibe: "Warm & playful",
    quote: "Mom to one amazing little girl. Lover of food, Netflix and weekend getaways.",
    decisionStyle: "Spontaneous, Peer-informed",
    platforms: ["Facebook", "Instagram", "WhatsApp", "TikTok"],
    traits: { "Tech affinity": 68, "Brand loyalty": 55 },
    profile:
      "Values practical parenting, authentic joy, work-life balance, and community entertainment. Warm, playful, and relatable messaging wins her over. Pretentious corporate speak or cold, clinical tones turn her off. Reached on social media during evening downtime after work. Highly price-sensitive, balancing budget needs with quality family experiences.",
  },
  {
    id: "otieno",
    name: "Otieno",
    segment: "Low Key Social Logistics Assistant",
    role: "Operations Assistant, Logistics Firm",
    age: 27,
    location: "Kenya",
    vibe: "Low Key",
    quote: "Football supporter. BBQs, family and good music. Just here for the laughs.",
    decisionStyle: "Spontaneous, Peer-led",
    platforms: ["Facebook", "Twitter / X", "WhatsApp"],
    traits: { "Tech affinity": 62, "Brand loyalty": 65 },
    profile:
      "Values sports camaraderie, relaxed leisure, family, and straightforward humor. Casual, lighthearted, and fun messaging wins him over. Drama, preachy lectures, and aggressive sales pitches turn him off. Consumes media primarily around football matchdays and weekend evenings. Moderately price-sensitive, seeking value to spend on social gatherings and match tickets.",
  },
  {
    id: "kamau-opiyo",
    name: "Kamau Opiyo",
    segment: "Hyper Passionate Local Football Creator",
    role: "Sports Content Creator & Harambee Stars Superfan",
    age: 25,
    location: "Kayole",
    vibe: "Terrace loudmouth",
    quote: "Gor Mahia deserved better today. That's all I'll say.",
    decisionStyle: "Spontaneous, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Team loyalty": 96, "Impulse posting": 77 },
    profile:
      "Values club pride, matchday excitement, and energetic fan culture. Loud, passionate, and banter-filled messaging wins him over. Corporate polish, bland neutrality, or disrespect for local football turn him off. Highly active on TikTok, X, and WhatsApp. Price-sensitive, prioritizing scarce budget for stadium tickets, jerseys, and quick bets.",
  },
  {
    id: "mwikali-wachira",
    name: "Mwikali Wachira",
    segment: "High Energy Local Sports Influencer",
    role: "Sports Content Creator & Harambee Stars Superfan",
    age: 22,
    location: "Dandora",
    vibe: "Stats-brain fan",
    quote: "AFC Leopards deserved better today. That's all I'll say.",
    decisionStyle: "Spontaneous, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Team loyalty": 89, "Impulse posting": 85 },
    profile:
      "Values match stats, team loyalty, and vibrant community banter. Authentic, energetic, and fan-focused messaging wins her over. Synthetic corporate speak or dismissive takes on local sports turn her off. Rapidly consumes and creates content on TikTok and Twitter/X. Price-sensitive, spending discretionary cash mainly on tickets and sports apparel.",
  },
  {
    id: "okoth-ndungu",
    name: "Okoth Ndungu",
    segment: "Energetic Harambee Stars Fan Creator",
    role: "Sports Content Creator & Harambee Stars Superfan",
    age: 28,
    location: "Nyalenda",
    vibe: "Chant leader",
    quote: "Harambee Stars deserved better today. That's all I'll say.",
    decisionStyle: "Spontaneous, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Team loyalty": 88, "Impulse posting": 80 },
    profile:
      "Values national team pride, terrace culture, and shared fan passion. Direct, spirited, and community-driven messaging wins him over. Overly polished PR or sanitized sports coverage turns him off. Heavy user of TikTok, X, and WhatsApp during matches. Highly price-sensitive, reserving funds for matchdays, kits, and small wagers.",
  },
  {
    id: "felix-achieng",
    name: "Felix Achieng",
    segment: "Skeptical Investigative Journalist & Anchor",
    role: "Multimedia Journalist & News Anchor",
    age: 35,
    location: "Westlands",
    vibe: "Skeptical Investigative",
    quote: "Statement from the ministry raises more questions than it answers. Thread coming.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Skepticism: 88, "Risk tolerance": 62, "Institutional trust": 28 },
    profile:
      "Values truth, accountability, and depth. Won over by transparent, evidence-based, direct messaging. Turned off by official rhetoric, rehearsed answers, and spin. Uses Twitter/X, LinkedIn, WhatsApp, and Facebook. High price sensitivity due to chronic underpayment, prioritizing clear value over hype.",
  },
  {
    id: "wanjiru-nabwire",
    name: "Wanjiru Nabwire",
    segment: "Field-First Investigative News Reporter",
    role: "Multimedia Journalist & News Anchor",
    age: 37,
    location: "South C",
    vibe: "Field-first reporter",
    quote: "Statement from the ministry raises more questions than it answers. Thread coming.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Skepticism: 84, "Risk tolerance": 67, "Institutional trust": 35 },
    profile:
      "Values factual accountability and independent probing. Responds to analytical, direct, transparent messaging. Turned off by corporate fluff, evasive PR, and unverified claims. Active on X/Twitter, LinkedIn, WhatsApp, and Facebook. Price-sensitive, carefully evaluating utility due to modest media salaries.",
  },
  {
    id: "okoth-kilonzo",
    name: "Okoth Kilonzo",
    segment: "Deadline-Driven Investigative Media Professional",
    role: "Multimedia Journalist & News Anchor",
    age: 40,
    location: "Nyali",
    vibe: "Deadline-Driven Investigative",
    quote: "Statement from the ministry raises more questions than it answers. Thread coming.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Skepticism: 88, "Risk tolerance": 62, "Institutional trust": 30 },
    profile:
      "Values institutional transparency and thorough inquiry. Won over by concise, evidence-led, objective tone. Turned off by scripted statements, surface-level messaging, and PR spin. Consumes news via X/Twitter, LinkedIn, WhatsApp, and Facebook. Price-sensitive, looking for high value and practical necessity.",
  },
  {
    id: "josphat-mutiso",
    name: "Josphat Mutiso",
    segment: "Community-Oriented Veteran Secondary Teacher",
    role: "Secondary School Teacher",
    age: 43,
    location: "Nyeri Town",
    vibe: "Community-Oriented Veteran",
    quote: "Proud of my form fours today. Hard work is starting to show.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Patience: 93, "Risk aversion": 68 },
    profile:
      "Values hard work, community trust, and long-term stability. Won over by warm, respectful, consensus-building messages. Turned off by high-risk schemes and flashy promises. Consumes content on WhatsApp, Facebook, YouTube, and Pinterest. Highly price-sensitive, relying on SACCOs and disciplined savings.",
  },
  {
    id: "jelagat-bashir",
    name: "Jelagat Bashir",
    segment: "Patient Mentoring Secondary Educator",
    role: "Secondary School Teacher",
    age: 32,
    location: "Kakamega",
    vibe: "Warm mentor",
    quote: "Proud of my form fours today. Hard work is starting to show.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Patience: 93, "Risk aversion": 68 },
    profile:
      "Values student growth, reliability, and community consensus. Won over by empathetic, practical, reassuring messaging. Turned off by sudden changes, arrogance, and risky ventures. Uses WhatsApp, Facebook, YouTube, and Pinterest. Highly price-sensitive, preferring risk-averse financial options like SACCOs.",
  },
  {
    id: "njoroge-mutua",
    name: "Njoroge Mutua",
    segment: "Disciplined Community Secondary Teacher",
    role: "Secondary School Teacher",
    age: 49,
    location: "Machakos",
    vibe: "Disciplined Community",
    quote: "Proud of my form fours today. Hard work is starting to show.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Patience: 93, "Risk aversion": 71 },
    profile:
      "Values tradition, patience, and stable progress. Won over by earnest, respectful, community-focused tone. Turned off by hype, rapid risk-taking, and flashiness. Relies on WhatsApp, Facebook, YouTube, and Pinterest. Very price-sensitive, carefully budgeting through SACCO savings groups.",
  },
  {
    id: "mutiso-waweru",
    name: "Mutiso Waweru",
    segment: "Networked Public Sector Policy Officer",
    role: "County Government Officer",
    age: 35,
    location: "Upper Hill",
    vibe: "Networked Public",
    quote: "Grateful for a productive stakeholder forum on public health today.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Institutional trust": 77, "Network orientation": 77 },
    profile:
      "Values public impact, professional networking, and discretion. Won over by collaborative, professional, process-oriented communication. Turned off by reckless statements and overt political bias. Uses WhatsApp, Facebook, LinkedIn, and Pinterest. Moderate price sensitivity, balancing public salary with long-term real estate investments.",
  },
  {
    id: "mercy-njuguna",
    name: "Mercy Njuguna",
    segment: "Ambitious Infrastructure Public Service Officer",
    role: "County Government Officer",
    age: 45,
    location: "Nakuru Town",
    vibe: "Quietly ambitious",
    quote: "Grateful for a productive stakeholder forum on roads and infrastructure today.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Institutional trust": 70, "Network orientation": 74 },
    profile:
      "Values local impact, structured policy, and professional reputation. Won over by measured, respectful, consensus-oriented tone. Turned off by loud controversy and unproven claims. Active on WhatsApp, Facebook, LinkedIn, and Pinterest. Moderately price-sensitive, prioritizing secure long-term investments like property.",
  },
  {
    id: "kiplagat-yusuf",
    name: "Kiplagat Yusuf",
    segment: "Process-Driven Public Finance Officer",
    role: "County Government Officer",
    age: 46,
    location: "Kisumu Town",
    vibe: "Process-Driven Public",
    quote: "Grateful for a productive stakeholder forum on revenue and finance today.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Institutional trust": 72, "Network orientation": 80 },
    profile:
      "Values order, institutional progress, and strong networks. Won over by pragmatic, low-key, structured messaging. Turned off by radical disruptions and careless messaging. Reached via WhatsApp, Facebook, LinkedIn, and Pinterest. Moderate price sensitivity, focusing budget on steady long-term assets.",
  },
  {
    id: "rose-achieng",
    name: "Rose Achieng",
    segment: "Resilient Micro-Entrepreneur Family Provider",
    role: "Mother & Small Business Owner",
    age: 42,
    location: "Kasarani",
    vibe: "Resilient Micro-Entrepreneur",
    quote: "New stock arrived for a small salon! Come through, mamas.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Resilience: 93, "Self-prioritisation": 37 },
    profile:
      "Values family stability, practical growth, and peer support. Won over by direct, encouraging, pragmatic messaging. Turned off by condescension, fluff, and unnecessary complexity. Uses WhatsApp, Facebook, TikTok, and Pinterest. Price-sensitive, maximizing value through chama savings and careful cash flow.",
  },
  {
    id: "nancy-otieno",
    name: "Nancy Otieno",
    segment: "Resilient Mother and Business Owner",
    role: "Mother & Small Business Owner",
    age: 34,
    location: "Thika",
    vibe: "Resilient Mother",
    quote: "New stock arrived for a school-uniform tailoring business! Come through, mamas.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Resilience: 87, "Self-prioritisation": 38 },
    profile:
      "Values family security, business stability, and community trust. A practical, supportive tone emphasizing practical growth wins her over. Preachy, patronizing messages turn her off. Active on WhatsApp, Facebook, TikTok, and Pinterest. Moderate to high price sensitivity; seeks reliable value for money to protect hard-earned savings.",
  },
  {
    id: "consolata-mwangi",
    name: "Consolata Mwangi",
    segment: "Protective Mother and Kiosk Entrepreneur",
    role: "Mother & Small Business Owner",
    age: 33,
    location: "Nakuru",
    vibe: "Fiercely protective",
    quote: "New stock arrived for a grocery kiosk! Come through, mamas.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Resilience: 92, "Self-prioritisation": 34 },
    profile:
      "Values family stability, practical safety, and peer support. Empathetic, encouraging messaging wins her over. Aggressive sales pitches or dismissive tones turn her off. Consumes WhatsApp, Facebook, TikTok, and Pinterest daily. Highly price-sensitive, balancing tight margins to secure her family’s financial future.",
  },
  {
    id: "barasa-yusuf",
    name: "Barasa Yusuf",
    segment: "Devoted Father and Professional Provider",
    role: "Father & Salaried Professional",
    age: 44,
    location: "Ngong Road",
    vibe: "Steady provider",
    quote: "SACCO contribution done for the month. Slow and steady.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Emotional restraint": 80, "Family orientation": 87 },
    profile:
      "Values family security, steady progress, and practical reliability. Clear, respectful, and deliberate messaging wins him over. Flashy promises or superficial claims turn him off. Reaches for WhatsApp, Facebook, YouTube, and Pinterest. Highly price-sensitive due to heavy financial loads, seeking dependable value.",
  },
  {
    id: "farah-noor",
    name: "Farah Noor",
    segment: "Steady Family Provider and Professional",
    role: "Father & Salaried Professional",
    age: 37,
    location: "Nakuru",
    vibe: "Steady Family",
    quote: "SACCO contribution done for the month. Slow and steady.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Emotional restraint": 75, "Family orientation": 94 },
    profile:
      "Values financial stability, long-term growth, and family well-being. Calm, trustworthy, and respectful tones win him over. Overly hype-driven or disrespectful messaging turns him off. Uses WhatsApp, Facebook, YouTube, and Pinterest. Very price-sensitive, balancing multiple family support obligations carefully.",
  },
  {
    id: "duncan-hassan",
    name: "Duncan Hassan",
    segment: "Experienced Professional and Family Anchor",
    role: "Father & Salaried Professional",
    age: 51,
    location: "Eldoret",
    vibe: "Experienced Professional",
    quote: "SACCO contribution done for the month. Slow and steady.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Emotional restraint": 80, "Family orientation": 91 },
    profile:
      "Values security, financial discipline, and family stability. A respectful, consensus-building, and pragmatic tone wins him over. Reckless, high-pressure messaging turns him off. Engages via WhatsApp, Facebook, YouTube, and Pinterest. Moderate to high price sensitivity, prioritizing long-term stability and value.",
  },
  {
    id: "ndungu-macharia",
    name: "Ndungu Macharia",
    segment: "Young Digital Skit Creator Entrepreneur",
    role: "Skit Creator & Stand-Up Comedian",
    age: 22,
    location: "Umoja",
    vibe: "Young Digital",
    quote: "POV: your mum finds the family WhatsApp group screenshot 💀",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Financial precarity tolerance": 58 },
    profile:
      "Values creative expression, online consistency, and humor. Fast-paced, authentic, and culturally relatable messaging wins him over. Corporate, dull, or overly formal tones turn him off. Lives on TikTok, Instagram, YouTube, and Pinterest. Moderately price-sensitive, open to tools boosting productivity or reach.",
  },
  {
    id: "ann-ouma",
    name: "Ann Ouma",
    segment: "Youth Comedy Creator and Influencer",
    role: "Skit Creator & Stand-Up Comedian",
    age: 22,
    location: "Rongai",
    vibe: "Youth Comedy",
    quote: "POV: your mum finds the family WhatsApp group screenshot 💀",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Financial precarity tolerance": 54 },
    profile:
      "Values audience engagement, relatable humor, and creative hustle. Direct, energetic, and culturally plugged-in tones win her over. Out-of-touch or condescending messaging turns her off. Frequent user of TikTok, Instagram, YouTube, and Pinterest. Price-sensitive, looking for low-cost, high-impact growth tools.",
  },
  {
    id: "farah-njiru",
    name: "Farah Njiru",
    segment: "Energetic Digital Comedy Content Creator",
    role: "Skit Creator & Stand-Up Comedian",
    age: 26,
    location: "Mombasa",
    vibe: "Energetic Digital",
    quote: "POV: your mum finds the family WhatsApp group screenshot 💀",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Financial precarity tolerance": 55 },
    profile:
      "Values audience growth, humor, and creative consistency. Witty, direct, and fast-paced messaging wins him over. Rigid, boring, or artificial messaging turns him off. Active across TikTok, Instagram, YouTube, and Pinterest. Moderate price sensitivity, prioritizing practical efficiency and engagement tools.",
  },
  {
    id: "kibet-mbogo",
    name: "Kibet Mbogo",
    segment: "Anonymous Online Drama Commentator",
    role: "Anonymous Online Commentator",
    age: 23,
    location: "unspecified",
    vibe: "Chronically online",
    quote:
      "Not me starting drama at 11pm on a Tuesday again. It's the algorithm's fault, not mine.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Anonymity comfort": 88, "Attention-seeking": 85 },
    profile:
      "Values digital anonymity, viral humor, and social engagement. Bold, witty, and provocative messaging wins him over. Preachy, restrictive, or overly serious tones turn him off. Exclusively active on Instagram. Low brand loyalty and price-conscious, preferring free or low-cost digital entertainment.",
  },
  {
    id: "amina-kiprono",
    name: "Amina Kiprono",
    segment: "Contrarian Anonymous Social Media User",
    role: "Anonymous Online Commentator",
    age: 27,
    location: "Nakuru",
    vibe: "Contrarian for sport",
    quote:
      "Not me starting drama at 11pm on a Tuesday again. It's the algorithm's fault, not mine.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Anonymity comfort": 88, "Attention-seeking": 80 },
    profile:
      "Values freedom of expression, unfiltered interaction, and privacy. Sharp, edgy, and clever messaging wins her over. Censorial, overly earnest, or moralizing tones turn her off. Primed for Instagram usage. Highly price-conscious, seeking free access and maximum digital flexibility.",
  },
  {
    id: "abdi-mbogo",
    name: "Abdi Mbogo",
    segment: "Anonymous Online Entertainment Commentator",
    role: "Anonymous Online Commentator",
    age: 25,
    location: "Mombasa",
    vibe: "Anonymous Online",
    quote:
      "Not me starting drama at 11pm on a Tuesday again. It's the algorithm's fault, not mine.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Anonymity comfort": 85, "Attention-seeking": 81 },
    profile:
      "Abdi values anonymity, clout, and online drama. Provocative, edgy, and trendy messaging wins him over. Heavy-handed moderation, preachy tones, and dull corporate speak turn him off. He lives on Instagram. Highly price-sensitive, seeking free or ultra-low-cost digital entertainment.",
  },
  {
    id: "brenda-wambua",
    name: "Brenda Wambua",
    segment: "Analytical Agricultural Research Scientist",
    role: "Research Scientist, Agricultural Biotechnology",
    age: 42,
    location: "Kabete",
    vibe: "Analytical Agricultural",
    quote:
      "New results on drought-resistant crop varieties are promising, though there's more work before we can say anything definitive.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Analytical rigour": 96, "Public communication comfort": 41 },
    profile:
      "Brenda values scientific rigor, practical agricultural impact, and mentorship. Pragmatic, data-driven messages with cautious optimism win her over. Exaggerated claims, sensationalism, and bureaucratic fluff turn her off. She uses LinkedIn, Twitter/X, WhatsApp, and Pinterest. Moderate price sensitivity, prioritizing research value and long-term utility.",
  },
  {
    id: "lucy-kiplagat",
    name: "Lucy Kiplagat",
    segment: "Quietly Rigorous Health Research Scientist",
    role: "Research Scientist, Agricultural Biotechnology",
    age: 43,
    location: "Nakuru",
    vibe: "Quietly brilliant",
    quote:
      "New results on malaria vector research are promising, though there's more work before we can say anything definitive.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Analytical rigour": 91, "Public communication comfort": 39 },
    profile:
      "Lucy values evidence-based results, public health impact, and supporting younger researchers. Analytical, respectful tones grounded in verifiable data win her over. Unsubstantiated hype and overly aggressive marketing turn her off. She frequents LinkedIn, Twitter/X, WhatsApp, and Pinterest. Moderate price sensitivity, focusing on proven quality over cost.",
  },
  {
    id: "nasimiyu-omondi",
    name: "Nasimiyu Omondi",
    segment: "Data Driven Soil Science Researcher",
    role: "Research Scientist, Agricultural Biotechnology",
    age: 40,
    location: "KEMRI",
    vibe: "Data over anecdote",
    quote:
      "New results on soil health and fertility mapping are promising, though there's more work before we can say anything definitive.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Analytical rigour": 98, "Public communication comfort": 43 },
    profile:
      "Nasimiyu values data accuracy, tangible agricultural outcomes, and scientific mentorship. Objective, clear, evidence-backed messaging wins her over. Emotional appeals without empirical backing turn her off. She is active on LinkedIn, Twitter/X, WhatsApp, and Pinterest. Moderate price sensitivity, preferring long-term practical ROI over cheap quick fixes.",
  },
  {
    id: "erick-yusuf",
    name: "Erick Yusuf",
    segment: "Ambitious First Generation University Student",
    role: "University Student",
    age: 22,
    location: "Chiromo",
    vibe: "Broke but hopeful",
    quote: "Survived another exam season. Barely. But I survived.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Ambition: 84, "Long-term planning": 48 },
    profile:
      "Erick values academic success, financial independence, and strong peer networks. Energetic, relatable, and hustle-friendly tones win him over. Elite condescension and expensive commitments turn him off. He uses TikTok, Instagram, WhatsApp, and Pinterest. Highly price-sensitive, constantly seeking affordable solutions and budget deals.",
  },
  {
    id: "nancy-njuguna",
    name: "Nancy Njuguna",
    segment: "Multitasking Student Content Creator",
    role: "University Student",
    age: 24,
    location: "Kikuyu",
    vibe: "Multitasking Student",
    quote: "Survived another exam season. Barely. But I survived.",
    decisionStyle: "Spontaneous, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Ambition: 89, "Long-term planning": 56 },
    profile:
      "Nancy values social mobility, peer consensus, and creative side hustles. Supportive, trendy, and community-focused messaging wins her over. Rigid formality and overly risky financial offers turn her off. She frequents TikTok, Instagram, WhatsApp, and Pinterest. Very price-sensitive, prioritizing high-value, low-cost essentials and trendy deals.",
  },
  {
    id: "antony-njoroge",
    name: "Antony Njoroge",
    segment: "Resourceful Ambitious Campus Tutor",
    role: "University Student",
    age: 19,
    location: "Eldoret, Kenya",
    vibe: "Resourceful Ambitious",
    quote: "Survived another exam season. Barely. But I survived.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Ambition: 83, "Long-term planning": 54 },
    profile:
      "Antony values self-reliance, academic achievement, and supportive friendships. Authentic, encouraging, and practical messaging wins him over. Arrogance, overly complex terms, and high costs turn him off. He consumes TikTok, Instagram, WhatsApp, and Pinterest. Highly price-sensitive, seeking budget-friendly options and side-gig opportunities.",
  },
  {
    id: "mueni-nabwire",
    name: "Mueni Nabwire",
    segment: "Senior Academic Development Economics Lecturer",
    role: "University Lecturer & Researcher",
    age: 64,
    location: "Chiromo",
    vibe: "Senior Academic",
    quote:
      "New paper on development economics finally out after two years. Slow science, but real.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Analytical rigour": 92, Formality: 80 },
    profile:
      "Mueni values intellectual depth, student development, and slow science. Thoughtful, understated, and intellectually honest tones win her over. Bureaucratic jargon, superficial trends, and rush jobs turn her off. She relies primarily on email. Low to moderate price sensitivity, prioritizing quality, reliability, and academic rigor.",
  },
  {
    id: "anyango-nzomo",
    name: "Anyango Nzomo",
    segment: "Formally Warm Public Health Academic",
    role: "University Lecturer & Researcher",
    age: 46,
    location: "Moi University",
    vibe: "Formally warm",
    quote: "New paper on public health policy finally out after two years. Slow science, but real.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Analytical rigour": 89, Formality: 85 },
    profile:
      "Anyango values academic integrity, real-world health policy, and mentoring next-gen scholars. Respectful, well-researched, and subtly humorous messaging wins her over. Pretentiousness, lack of rigor, and pushy sales tactics turn her off. She relies heavily on email. Low to moderate price sensitivity, preferring reliable professional value.",
  },
  {
    id: "asha-wachira",
    name: "Asha Wachira",
    segment: "Postcolonial Literature Academic Researcher",
    role: "University Lecturer & Researcher",
    age: 42,
    location: "Njoro, Kenya",
    vibe: "Postcolonial Literature",
    quote:
      "New paper on literature and postcolonial studies finally out after two years. Slow science, but real.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Analytical rigour": 89, Formality: 77 },
    profile:
      "Asha values deep scholarship, postcolonial perspectives, and meaningful mentorship. Articulate, nuanced, and dryly witty tones win her over. Fluff, administrative nonsense, and shallow arguments turn her off. She uses email as her primary channel. Low to moderate price sensitivity, prioritizing intellectual substance over financial cost.",
  },
  {
    id: "charles-wekesa",
    name: "Charles Wekesa",
    segment: "Urban Matatu Driver Community Leader",
    role: "Matatu Driver, Route 58",
    age: 28,
    location: "Kayole, Nairobi",
    vibe: "Urban Matatu",
    quote: "route 58 traffic today was something else. God is faithful, we still made it.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Street awareness": 96, "Institutional trust": 48 },
    profile:
      "Values sacco solidarity and long-term fleet ownership. Respectful, practical messaging highlighting reliability wins him over; condescension and corporate jargon turn him off. Active on WhatsApp, Facebook, TikTok, and Pinterest. Extremely price-sensitive due to thin daily operating margins.",
  },
  {
    id: "chepkoech-gichuru",
    name: "Chepkoech Gichuru",
    segment: "Experienced Route Operator Matatu Driver",
    role: "Matatu Driver, Route 58",
    age: 49,
    location: "Rongai, Nairobi",
    vibe: "Experienced Route",
    quote: "the Rongai route traffic today was something else. God is faithful, we still made it.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Street awareness": 88, "Institutional trust": 44 },
    profile:
      "Values sacco network strength and long-term business growth. Direct, practical messaging around financial resilience wins her over; rigid corporate lecturing turns her off. Frequently uses WhatsApp, Facebook, TikTok, and Pinterest. Very price-sensitive due to slim daily profit margins.",
  },
  {
    id: "felix-owino",
    name: "Felix Owino",
    segment: "Resilient Coast Transit Matatu Driver",
    role: "Matatu Driver, Route 58",
    age: 40,
    location: "Likoni, Mombasa",
    vibe: "Resilient Coast",
    quote:
      "the Likoni ferry crossing route traffic today was something else. God is faithful, we still made it.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Street awareness": 89, "Institutional trust": 48 },
    profile:
      "Values sacco support and building independent fleet ownership. Grounded, peer-level messages promising real savings win him over; patronizing or overly complex offers turn him off. Engages via WhatsApp, Facebook, TikTok, and Pinterest. Highly price-sensitive given volatile daily expense margins.",
  },
  {
    id: "munyao-wanyonyi",
    name: "Munyao Wanyonyi",
    segment: "Established Wholesale Textile Retail Operator",
    role: "Small Business Owner, Retail & Wholesale",
    age: 52,
    location: "Eastleigh",
    vibe: "Shrewd negotiator",
    quote:
      "New stock in for a clothing and textile shop. Come see before it moves - it always moves fast.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Financial shrewdness": 93, Persistence: 97 },
    profile:
      "Values network trust, credit reputation, and reinvestment for family security. Shrewd, ROI-focused messages emphasizing stability win him over; risky or flashy promises turn him off. Relies on WhatsApp, Facebook, TikTok, and Pinterest. Extremely price-conscious and highly strategic regarding capital investments.",
  },
  {
    id: "ndinda-langat",
    name: "Ndinda Langat",
    segment: "Resilient Urban Electronics Stall Owner",
    role: "Small Business Owner, Retail & Wholesale",
    age: 47,
    location: "River Road",
    vibe: "Relentless hustler",
    quote:
      "New stock in for an electronics and phone-accessories stall. Come see before it moves - it always moves fast.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Financial shrewdness": 93, Persistence: 90 },
    profile:
      "Values community goodwill, business resilience, and family legacy. Pragmatic, trust-centric messaging highlighting profit margin improvements wins her over; unverified claims turn her off. Active on WhatsApp, Facebook, TikTok, and Pinterest. Highly price-sensitive, carefully weighing every commercial expense.",
  },
  {
    id: "otieno-noor",
    name: "Otieno Noor",
    segment: "Community Hardware Wholesale Business Owner",
    role: "Small Business Owner, Retail & Wholesale",
    age: 40,
    location: "Kongowea",
    vibe: "Community pillar",
    quote:
      "New stock in for a hardware and building-materials outlet. Come see before it moves - it always moves fast.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Financial shrewdness": 87, Persistence: 90 },
    profile:
      "Values trader solidarity, financial prudence, and building lasting family assets. Honest, clear-cut offers demonstrating immediate margin utility win him over; abstract marketing turns him off. Uses WhatsApp, Facebook, TikTok, and Pinterest. Very price-sensitive, constantly seeking high-value terms for stock purchases.",
  },
  {
    id: "charles-hassan",
    name: "Charles Hassan",
    segment: "Energetic Nightlife Promoter Social Connector",
    role: "Nightlife Enthusiast & Events Promoter",
    age: 25,
    location: "Westlands",
    vibe: "Energetic Nightlife",
    quote: "a Friday rooftop night was UNREAL last night. Still recovering. Worth every bit of it.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Extraversion: 94, "Social network breadth": 95 },
    profile:
      "Values vibrant social experiences, peer networks, and emerging career opportunities. High-energy, trend-conscious messaging with social proof wins him over; formal or dull copy turns him off. Heavy user of Instagram, TikTok, WhatsApp, and Pinterest. Moderately price-sensitive, balancing lifestyle spending with financial ambition.",
  },
  {
    id: "ndinda-mburu",
    name: "Ndinda Mburu",
    segment: "Trendsetting Urban Event Experience Organizer",
    role: "Nightlife Enthusiast & Events Promoter",
    age: 25,
    location: "Kilimani",
    vibe: "Trendsetting Urban",
    quote: "a beach party in Diani was UNREAL last night. Still recovering. Worth every bit of it.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Extraversion: 89, "Social network breadth": 95 },
    profile:
      "Values lifestyle aesthetics, social influence, and long-term security. Stylish, upbeat copy with genuine social backing wins her over; rigid or outdated messaging turns her off. Reached via Instagram, TikTok, WhatsApp, and Pinterest. Moderately price-sensitive, willing to spend on high-impact social experiences.",
  },
  {
    id: "maina-bashir",
    name: "Maina Bashir",
    segment: "High Energy Youth Events Promoter",
    role: "Nightlife Enthusiast & Events Promoter",
    age: 26,
    location: "Nyali",
    vibe: "High Energy",
    quote:
      "a hip-hop night downtown was UNREAL last night. Still recovering. Worth every bit of it.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Extraversion: 92, "Social network breadth": 97 },
    profile:
      "Values nightlife culture, trusted social circles, and future progress. Bold, hype-focused messages grounded in community appeal win him over; stuffy or clinical tones turn him off. Highly active on Instagram, TikTok, WhatsApp, and Pinterest. Moderately price-sensitive, prioritizing high-value lifestyle engagements.",
  },
  {
    id: "barasa-noor",
    name: "Barasa Noor",
    segment: "Focused Developer Gaming Community Enthusiast",
    role: "Software Developer & Gamer",
    age: 21,
    location: "Kilimani",
    vibe: "Focused Developer",
    quote:
      "Finally fixed the bug that's been haunting this project for a week. Small win, big relief.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Focus/flow capacity": 91, "Risk tolerance": 38 },
    profile:
      "Values technical mastery, online gaming communities, and deliberate skill-building. Clear, logical, fluff-free messaging wins him over; superficial hype and small talk turn him off. Main platforms are Discord, Reddit, Twitter/X, and Pinterest. Moderately price-sensitive, prioritizing quality utility and tools over cost.",
  },
  {
    id: "rashid-onyango",
    name: "Rashid Onyango",
    segment: "Independent Urban Tech and Gamer",
    role: "Software Developer & Gamer",
    age: 22,
    location: "Lavington",
    vibe: "Independent Urban",
    quote:
      "Finally fixed the bug that's been haunting this project for a week. Small win, big relief.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Focus/flow capacity": 89, "Risk tolerance": 43 },
    profile:
      "Values technical mastery, deep niche communities, and building projects. A precise, authentic, direct tone wins him over. Avoid small talk, fluff, and superficial marketing. Active on Discord, Reddit, Twitter, and Pinterest. He is moderately price-sensitive, prioritizing utility, performance, and practical value over brand prestige.",
  },
  {
    id: "kibet-abdi",
    name: "Kibet Abdi",
    segment: "Quietly Competitive Tech Developer Gamer",
    role: "Software Developer & Gamer",
    age: 23,
    location: "Ngong Road",
    vibe: "Quietly competitive",
    quote:
      "Finally fixed the bug that's been haunting this project for a week. Small win, big relief.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Focus/flow capacity": 94, "Risk tolerance": 41 },
    profile:
      "Values skill building, deep focus, and dedicated online communities. An authentic, detailed, respectful tone resonates well. Avoid fluff, forced social interaction, and patronizing jargon. He frequents Discord, Reddit, Twitter, and Pinterest. He exhibits moderate price sensitivity, seeking high utility and solid ROI for his tools.",
  },
  {
    id: "john-simiyu",
    name: "John Simiyu",
    segment: "Patient Rural Smallholder Tea Farmer",
    role: "Smallholder Farmer",
    age: 62,
    location: "Nyeri County, Kenya",
    vibe: "Patient Rural",
    quote: "Good rains this week, alhamdulillah / thank God. The maize is finally recovering.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Patience: 90, "Community reciprocity": 86 },
    profile:
      "Values community reciprocity, long-term stability, and hard-earned farming wisdom. A respectful, unhurried, trust-building tone wins him over. Avoid pushy sales pitches and flashy promises. Reached primarily via radio. Highly price-sensitive, focusing on cost efficiency, proven reliability, and lasting multi-generational value.",
  },
  {
    id: "wambui-kiprono",
    name: "Wambui Kiprono",
    segment: "Community Focused Rural Smallholder Farmer",
    role: "Smallholder Farmer",
    age: 39,
    location: "Kakamega County",
    vibe: "Community Focused",
    quote: "Good rains this week, alhamdulillah / thank God. The maize is finally recovering.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Patience: 90, "Community reciprocity": 91 },
    profile:
      "Values shared community labor, practical yields, and long-term family security. A warm, practical, consensus-seeking tone wins her over. Avoid aggressive tactics and unrealistic quick fixes. Reached via radio media. She is highly price-sensitive, prioritizing affordable input costs and proven, low-risk practical utility.",
  },
  {
    id: "cheruiyot-ochieng",
    name: "Cheruiyot Ochieng",
    segment: "Independent Urban Boda Boda Operator",
    role: "Boda Boda Rider",
    age: 21,
    location: "Kawangware",
    vibe: "Fast and fearless",
    quote: "the Kawangware–CBD run was smooth today. Fuel price still biting though.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Risk tolerance": 76, "Institutional trust": 37 },
    profile:
      "Values financial independence, peer solidarity, and growth opportunities. An energetic, straightforward, empowering message wins him over. Avoid bureaucratic delays, condescension, and rigid terms. Consumes WhatsApp, Facebook, TikTok, and Pinterest. He is price-sensitive, constantly managing tight daily cash flow and fuel expenses.",
  },
  {
    id: "winnie-wanyonyi",
    name: "Winnie Wanyonyi",
    segment: "Enterprise Minded Boda Boda Hustler",
    role: "Boda Boda Rider",
    age: 29,
    location: "Githurai",
    vibe: "Hustler's hustler",
    quote:
      "school-run contracts with local parents was smooth today. Fuel price still biting though.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Risk tolerance": 78, "Institutional trust": 45 },
    profile:
      "Values practical entrepreneurship, peer support, and income diversification. A direct, motivating, action-oriented tone wins her over. Avoid corporate fluff, delays, and patronizing language. Active on WhatsApp, Facebook, TikTok, and Pinterest. Highly price-sensitive due to daily fuel costs, seeking flexible financial terms.",
  },
  {
    id: "waithera-wekesa",
    name: "Waithera Wekesa",
    segment: "Dedicated Hospital Nurse Union Advocate",
    role: "Registered Nurse, County Hospital",
    age: 34,
    location: "Nairobi, Kenya",
    vibe: "Dedicated Hospital",
    quote: "Twelve-hour shift done. Proud of my team today. We held it together.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Stress resilience": 88, "Burnout risk": 70 },
    profile:
      "Values team solidarity, patient care, and work-life balance. Empathetic, respectful, practical messaging wins her over. Avoid hollow praise and unsupportive demands. Reached through WhatsApp, Facebook, Twitter, and Pinterest. Moderately price-sensitive, seeking practical, stress-reducing solutions that offer reliable quality and long-term convenience.",
  },
  {
    id: "adhiambo-wachira",
    name: "Adhiambo Wachira",
    segment: "Resilient Hospital Emergency Room Nurse",
    role: "Registered Nurse, County Hospital",
    age: 43,
    location: "Nakuru",
    vibe: "Resilient Hospital",
    quote: "Twelve-hour shift done. Proud of my team today. We held it together.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Stress resilience": 87, "Burnout risk": 76 },
    profile:
      "Values professional teamwork, clear boundaries, and genuine recognition. A direct, empathetic, pragmatic tone wins her over. Avoid empty platitudes, emotional manipulation, and waste of time. Engages via WhatsApp, Facebook, Twitter, and Pinterest. She shows moderate price sensitivity, prioritizing quality, reliability, and value.",
  },
  {
    id: "kilonzo-wangari",
    name: "Kilonzo Wangari",
    segment: "Evidence Based General Practice Physician",
    role: "Medical Doctor, General Practice",
    age: 55,
    location: "Nairobi, Kenya",
    vibe: "Evidence Based",
    quote: "No, that home remedy does not cure what you think it cures. Please see a doctor.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Clinical confidence": 89, "Skepticism of misinformation": 88 },
    profile:
      "Values clinical accuracy, evidence-based truth, and protected family time. A concise, authoritative, peer-to-peer professional tone wins him over. Avoid sensational claims, pseudoscience, and vague marketing. Uses WhatsApp, Twitter, LinkedIn, and Pinterest. Price sensitivity is low to moderate, favoring clinical efficiency and verified efficacy.",
  },
  {
    id: "brenda-achieng",
    name: "Brenda Achieng",
    segment: "Evidence Driven Pediatric Medical Specialist",
    role: "Medical Doctor, General Practice",
    age: 41,
    location: "Hospital",
    vibe: "Evidence Driven",
    quote: "No, that home remedy does not cure what you think it cures. Please see a doctor.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Clinical confidence": 87, "Skepticism of misinformation": 87 },
    profile:
      "Values scientific integrity, solid evidence, and efficient patient care. A professional, direct, fact-based message wins her over. Avoid unverified health claims, fluff, and high-pressure tactics. Consumes media on WhatsApp, Twitter, LinkedIn, and Pinterest. Moderately price-sensitive, willing to invest in proven, high-quality professional solutions.",
  },
  {
    id: "omondi-wafula",
    name: "Omondi Wafula",
    segment: "Faith Community Leader and Deliberate Advocate",
    role: "Church Pastor & Community Leader",
    age: 36,
    location: "Kayole",
    vibe: "Faith Community",
    quote: "Sunday service was a blessing. Grateful for this congregation's faith and generosity.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Persuasiveness: 94, "Public accountability comfort": 63 },
    profile:
      "Omondi values community impact, faith, and shared decision-making. He is won over by respectful, consultative messages emphasizing collective good and accountability. Hard sells and rushed offers turn him off. He frequents WhatsApp, Facebook, and YouTube. Highly price-sensitive due to limited organizational resources, requiring clear value.",
  },
  {
    id: "felix-kimani",
    name: "Felix Kimani",
    segment: "Grassroots Faith and Community Organizer",
    role: "Church Pastor & Community Leader",
    age: 40,
    location: "Nakuru",
    vibe: "Grassroots Faith",
    quote: "Sunday service was a blessing. Grateful for this congregation's faith and generosity.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Persuasiveness: 90, "Public accountability comfort": 67 },
    profile:
      "Felix values youth empowerment, consensus, and moral integrity. Consultative, persuasive messaging focusing on community uplift resonates best. Rushed decisions and unvetted claims turn him off. He uses WhatsApp, Facebook, and YouTube daily. Highly price-conscious, he evaluates expenditures carefully to protect limited shared community funds.",
  },
  {
    id: "kamau-cheruiyot",
    name: "Kamau Cheruiyot",
    segment: "Independent Youth Music Content Creator",
    role: "Musician & Recording Artist",
    age: 21,
    location: "South B",
    vibe: "Independent Youth",
    quote:
      "a new Afrobeats-Gengetone crossover single dropping soon. Been in the studio every night for this one.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Creative openness": 96 },
    profile:
      "Kamau values artistic freedom, self-expression, and creative control. Direct, authentic, and inspiring messaging wins him over, while corporate overreach or rigid terms turn him off. He relies heavily on Instagram, TikTok, and YouTube. Navigating financial instability makes him budget-conscious, though he prioritizes creative tools over costs.",
  },
  {
    id: "muturi-otieno",
    name: "Muturi Otieno",
    segment: "Independent Urban Musician and Producer",
    role: "Musician & Recording Artist",
    age: 35,
    location: "Eastlands",
    vibe: "Independent Urban",
    quote:
      "a gospel-influenced R&B project dropping soon. Been in the studio every night for this one.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Creative openness": 94 },
    profile:
      "Muturi values creative autonomy and perfectionism in his craft. Authentic, artist-focused messages that respect his independence win him over. Restrictive contracts and corporate fluff turn him off. He engages mostly on TikTok, Instagram, and YouTube. Experiencing fluctuating income, he remains budget-conscious but invests selectively in production quality.",
  },
  {
    id: "millicent-odhiambo",
    name: "Millicent Odhiambo",
    segment: "Resilient Urban Small Market Trader",
    role: "Market Trader (Mama Mboga)",
    age: 32,
    location: "Gikomba",
    vibe: "Resilient Urban",
    quote:
      "Fresh fresh vegetables and greens today, good prices for my regulars. Come early before it's gone.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Resilience: 89, "Community warmth": 87 },
    profile:
      "Millicent values financial discipline, family security, and trusted networks. Warm, practical messaging emphasizing reliable profits and low risk wins her over. Hidden fees and fast-talk turn her off. She is active on WhatsApp and Facebook. Highly price-sensitive, she carefully calculates every expense against daily market cash flow.",
  },
  {
    id: "ann-njiru",
    name: "Ann Njiru",
    segment: "Veteran Micro Trader and Community Saver",
    role: "Market Trader (Mama Mboga)",
    age: 55,
    location: "Muthurwa",
    vibe: "Early riser",
    quote:
      "Fresh fruit and seasonal produce today, good prices for my regulars. Come early before it's gone.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Resilience: 95, "Community warmth": 86 },
    profile:
      "Ann values long-term security, financial discipline, and trusted community bonds. Straightforward, respectful pitches highlighting proven value and safety win her over. Complex terms and unpredictable costs turn her off. She communicates via WhatsApp and Facebook. Extremely price-sensitive, she meticulously manages daily profits for family and savings.",
  },
  {
    id: "langat-ouma",
    name: "Langat Ouma",
    segment: "Ambitious Urban Transport Worker",
    role: "Matatu Conductor",
    age: 18,
    location: "Umoja",
    vibe: "Fast-talking hustler",
    quote: "the Umoja–CBD route was chaos today but we made every trip. Hustle never stops.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Street awareness": 93, "Institutional trust": 36 },
    profile:
      "Langat values daily earnings, street smarts, and personal advancement. Energetic, direct messages showing immediate earnings or career progression win him over. Institutional bureaucracy and slow processes turn him off. He consumes content on TikTok and WhatsApp. Extremely price-conscious, he evaluates offers strictly by immediate cash-flow impact.",
  },
  {
    id: "wambua-wachira",
    name: "Wambua Wachira",
    segment: "Independent Public Transport Crew Member",
    role: "Matatu Conductor",
    age: 27,
    location: "Kayole",
    vibe: "Independent Public",
    quote: "the Kayole route was chaos today but we made every trip. Hustle never stops.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Street awareness": 88, "Institutional trust": 34 },
    profile:
      "Wambua values self-reliance, practical growth, and daily cash flow. Straightforward, high-energy messaging grounded in street reality wins him over. Preachy tones and formal roadblocks turn him off. He frequents TikTok, WhatsApp, and Facebook. Low trust in institutions and thin margins make him price-sensitive and focused on fast value.",
  },
  {
    id: "beatrice-hassan",
    name: "Beatrice Hassan",
    segment: "Creative Boutique Owner and Designer",
    role: "Fashion Designer & Boutique Owner",
    age: 27,
    location: "Kilimani",
    vibe: "Visually obsessive",
    quote:
      "a modern Ankara and kitenge fusion line sneak peek. Two months of work going into every piece.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Creative perfectionism": 88, "Financial discipline": 60 },
    profile:
      "Beatrice values artisanal quality, design integrity, and fair partnerships. Visually compelling, collaborative messaging that honors process wins her over. Rushed production demands or generic sales pitches turn her off. She uses Instagram, TikTok, and Pinterest. Moderately price-sensitive, prioritizing long-term quality and unique materials over cheap fixes.",
  },
  {
    id: "jepkorir-langat",
    name: "Jepkorir Langat",
    segment: "High End Fashion Boutique Designer",
    role: "Fashion Designer & Boutique Owner",
    age: 24,
    location: "Karen",
    vibe: "High End",
    quote:
      "a bridal and occasion-wear collection sneak peek. Two months of work going into every piece.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Creative perfectionism": 96, "Financial discipline": 65 },
    profile:
      "Jepkorir values creative perfectionism, premium craft, and artistic independence. Refined, inspiring messaging that highlights quality and partnership wins her over. Mass-market shortcuts and aggressive sales tactics turn her off. She relies on Instagram, TikTok, and Pinterest. She is moderately price-sensitive, willingly spending more on superior materials and craftsmanship.",
  },
  {
    id: "samuel-macharia",
    name: "Samuel Macharia",
    segment: "Disciplined Long Distance Marathon Athlete",
    role: "Long-Distance Runner",
    age: 23,
    location: "Elgeyo-Marakwet",
    vibe: "Disciplined Long",
    quote:
      "a marathon debut training block complete. Grateful for this body, this group, this journey.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Discipline: 96, "Long-term planning": 87 },
    profile:
      "Values communal discipline and long-term land investment over short-term flash. Respectful, pragmatic messaging emphasizing endurance and steady growth wins him over, while superficial hype turns him off. Active on Instagram, Facebook, and WhatsApp, he shows high price sensitivity, prioritising long-term security over impulse buys.",
  },
  {
    id: "jepkorir-mohamed",
    name: "Jepkorir Mohamed",
    segment: "Disciplined Circuit Half Marathon Runner",
    role: "Long-Distance Runner",
    age: 20,
    location: "Eldoret",
    vibe: "Disciplined Circuit",
    quote:
      "a half-marathon circuit season training block complete. Grateful for this body, this group, this journey.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Discipline: 93, "Long-term planning": 82 },
    profile:
      "Values communal athletic discipline and tangible, long-term financial security. Humble, practical messaging highlighting steady effort wins her over, whereas flashy hype turns her off. She uses Instagram, Facebook, and WhatsApp daily, demonstrating high price sensitivity by strictly directing funds toward lasting assets rather than short-term consumption.",
  },
  {
    id: "amina-kiprop",
    name: "Amina Kiprop",
    segment: "Grassroots Civic and Accountability Activist",
    role: "Civic & Human Rights Activist",
    age: 32,
    location: "Kibera",
    vibe: "Grassroots Civic",
    quote: "police accountability advocacy update - this fight isn't over, and neither are we.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Conviction: 96, "Community rootedness": 90 },
    profile:
      "Values grassroots justice, community solidarity, and authentic local impact. Urgent, conviction-led messaging wins her over, whereas performative rhetoric or corporate doublespeak turns her off immediately. Highly active on Twitter/X, Instagram, and WhatsApp, she exhibits strong price sensitivity, carefully allocating limited resources toward high-impact community solutions.",
  },
  {
    id: "waithera-owino",
    name: "Waithera Owino",
    segment: "Grassroots Housing Rights Community Activist",
    role: "Civic & Human Rights Activist",
    age: 29,
    location: "Mathare",
    vibe: "Grassroots Housing",
    quote: "housing and eviction rights update - this fight isn't over, and neither are we.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Conviction: 97, "Community rootedness": 93 },
    profile:
      "Values authentic community empowerment and tangible local human rights progress. Direct, action-oriented messaging wins her over, while top-down, patronizing, or superficial claims turn her off. She relies on Twitter/X, Instagram, and WhatsApp for communication and displays high price sensitivity, stretching resources carefully for maximum community benefit.",
  },
  {
    id: "wekesa-omondi",
    name: "Wekesa Omondi",
    segment: "Resilient Fintech Startup Tech Founder",
    role: "Startup Founder, Fintech",
    age: 38,
    location: "Kilimani",
    vibe: "Resilient Fintech",
    quote:
      "a mobile savings and micro-lending app just crossed a milestone I didn't think we'd hit this year. Grateful to this team.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Risk tolerance": 85, Resilience: 84 },
    profile:
      "Values practical ROI, team loyalty, and genuine business growth. Sharp, data-backed messaging wins him over, whereas vague pitch fluff and unverified promises turn him off. Reachable on LinkedIn, Twitter/X, and WhatsApp, he maintains high price sensitivity due to strict startup runway calculations, favoring efficient, high-value solutions.",
  },
  {
    id: "rukia-muturi",
    name: "Rukia Muturi",
    segment: "Strategic SME Fintech Startup Founder",
    role: "Startup Founder, Fintech",
    age: 37,
    location: "Westlands",
    vibe: "Pitch-deck fluent",
    quote:
      "a supply-chain payments platform for SMEs just crossed a milestone I didn't think we'd hit this year. Grateful to this team.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Risk tolerance": 88, Resilience: 83 },
    profile:
      "Values operational stability, team commitment, and measurable economic value. Concrete, business-minded messaging emphasizing proven efficiency wins her over, while manipulative sales hype turns her off. She frequents LinkedIn, Twitter/X, and WhatsApp, operating with strong price sensitivity and evaluating every purchase against strict operational budget impact.",
  },
  {
    id: "daniel-odhiambo",
    name: "Daniel Odhiambo",
    segment: "Security Minded Urban Traffic Officer",
    role: "Police Officer, County Traffic Unit",
    age: 31,
    location: "CBD",
    vibe: "Security Minded",
    quote: "Long shift, home safe. Grateful for that every single time.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Institutional loyalty": 72, "Risk tolerance": 66 },
    profile:
      "Values stability, peer support, and quiet personal integrity. Respectful, practical messaging emphasizing safety and security wins him over, whereas judgmental or overly complex tone turns him off. He connects via WhatsApp and Facebook, demonstrating cautious price sensitivity and relying on SACCO savings to maintain financial stability.",
  },
  {
    id: "vincent-hassan",
    name: "Vincent Hassan",
    segment: "Community Focused Coastal Police Officer",
    role: "Police Officer, County Traffic Unit",
    age: 34,
    location: "Mombasa",
    vibe: "Quietly weary",
    quote: "Long shift, home safe. Grateful for that every single time.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Institutional loyalty": 73, "Risk tolerance": 62 },
    profile:
      "Values steady security, family wellbeing, and peer solidarity. Straightforward, reassuring messaging focused on reliability wins him over, while confrontational or flashy tone turns him off. He uses WhatsApp and Facebook regularly, maintaining high price sensitivity through disciplined SACCO-based financial planning to protect his household budget.",
  },
  {
    id: "mwangangi-kiptoo",
    name: "Mwangangi Kiptoo",
    segment: "Vigilant Commercial Estate Security Guard",
    role: "Security Guard, Commercial Estate",
    age: 49,
    location: "Westlands",
    vibe: "Vigilant Commercial",
    quote: "Quiet shift tonight, grateful for that. Some nights you want boring.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Vigilance: 84, "Financial pragmatism": 76 },
    profile:
      "Values reliability, quiet pride, and steady routines. Honest, respectful messaging emphasizing dependable value wins him over, whereas arrogant tone or hidden costs turn him off. Reachable on WhatsApp and Facebook, he displays extreme price sensitivity, managing a modest budget carefully through mutual aid and small SACCO groups.",
  },
  {
    id: "nasimiyu-munyao",
    name: "Nasimiyu Munyao",
    segment: "Observant Residential Community Security Guard",
    role: "Security Guard, Commercial Estate",
    age: 24,
    location: "Upper Hill",
    vibe: "Quietly observant",
    quote: "Quiet shift tonight, grateful for that. Some nights you want boring.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Vigilance: 85, "Financial pragmatism": 75 },
    profile:
      "Values quiet steadiness, practical advancement, and financial discipline. Clear, encouraging messaging focused on practical benefit wins her over, while condescending or overly flashy tone turns her off. She uses WhatsApp and Facebook, showing high price sensitivity as she carefully manages delayed earnings through tight budgeting and guard SACCOs.",
  },
  {
    id: "kavata-chepkwony",
    name: "Kavata Chepkwony",
    segment: "Independent Fine Dining Culinary Artist",
    role: "Chef & Caterer",
    age: 33,
    location: "Kilimani",
    vibe: "Independent Fine",
    quote:
      "a modern Kenyan fine-dining pop-up menu testing tonight. My kitchen smells incredible right now.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Tech affinity": 68, "Brand loyalty": 60 },
    profile:
      "She values culinary craft and authentic dining reactions. Passionate, creative messaging honoring modern African gastronomy wins her over, while rigid corporate fluff turns her off. Active on Instagram, TikTok, Facebook, and Pinterest, she displays moderate price sensitivity, prioritizing quality ingredients and kitchen gear over cheap deals.",
  },
  {
    id: "khaemba-karanja",
    name: "Khaemba Karanja",
    segment: "Event Catering Creative Culinary Entrepreneur",
    role: "Chef & Caterer",
    age: 33,
    location: "Karen",
    vibe: "Warm host energy",
    quote:
      "a wedding and events catering business menu testing tonight. My kitchen smells incredible right now.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Tech affinity": 65, "Brand loyalty": 70 },
    profile:
      "He values hospitality, event excellence, and client reactions. Warm, professional messaging emphasizing reliability and craft wins him over, whereas toxic hustle culture turns him off. He uses Instagram, TikTok, Facebook, and Pinterest. He exhibits moderate price sensitivity, seeking value and high quality for large-scale catering investments.",
  },
  {
    id: "omondi-nyaga",
    name: "Omondi Nyaga",
    segment: "Energetic Media Personality and DJ",
    role: "Radio Presenter & DJ",
    age: 34,
    location: "Westlands",
    vibe: "Big on-air energy",
    quote: "Today's a morning drive-time show show was a vibe. Thank you for calling in, always.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "On-air extraversion": 95, "Public visibility comfort": 80 },
    profile:
      "He values listener engagement and side-income opportunities. Energetic, authentic partnerships win him over, while fake hype or low-paying deals turn him off. He checks Instagram, TikTok, X, and Pinterest daily. He is moderately price-sensitive, balancing personal hustle with high earnings potential to bridge income gaps.",
  },
  {
    id: "jematia-khaemba",
    name: "Jematia Khaemba",
    segment: "Community Focused Radio Host Presenter",
    role: "Radio Presenter & DJ",
    age: 26,
    location: "Mombasa",
    vibe: "Community voice",
    quote:
      "Today's an evening request and dedications show show was a vibe. Thank you for calling in, always.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "On-air extraversion": 96, "Public visibility comfort": 79 },
    profile:
      "She values listener engagement, community voice, and monetization. Dynamic, relational pitches win her over, while transactional corporate tone turns her off. She favors Instagram, TikTok, X, and Pinterest. She is price-sensitive due to income lag behind fame, actively seeking lucrative brand partnerships and affordable tech tools.",
  },
  {
    id: "peter-ochieng",
    name: "Peter Ochieng",
    segment: "Sustainable Lake Fisheries Cooperative Member",
    role: "Fisherman, Lake Victoria",
    age: 38,
    location: "Dunga Beach",
    vibe: "Sustainable Lake",
    quote: "Good catch this morning, tilapia and Nile perch fishing paying off the early start.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Patience: 92, "Environmental concern": 83 },
    profile:
      "He values ancestral tradition, community consensus, and lake conservation. Collaborative, respectful messaging highlighting sustainability wins him over, while aggressive sales tactics turn him off. He relies on WhatsApp, Facebook, LinkedIn, and Pinterest. Highly price-sensitive, he seeks durable, economical gear that protects his livelihood and family's future.",
  },
  {
    id: "kiprono-mutiso",
    name: "Kiprono Mutiso",
    segment: "Traditional Conservation Minded Senior Fisherman",
    role: "Fisherman, Lake Victoria",
    age: 58,
    location: "Homa Bay",
    vibe: "Traditional Conservation",
    quote: "Good catch this morning, a small fishing cooperative paying off the early start.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { Patience: 90, "Environmental concern": 80 },
    profile:
      "He values generational wisdom, cooperative agreement, and environmental protection. Patient, community-focused messages emphasizing sustainability win him over, whereas top-down pushes turn him off. He uses WhatsApp, Facebook, LinkedIn, and Pinterest. Highly price-sensitive, he cautiously evaluates costs to ensure long-term stability for his family and peers.",
  },
  {
    id: "nzomo-kagwe",
    name: "Nzomo Kagwe",
    segment: "Cultural Storytelling Independent Safari Guide",
    role: "Safari & Cultural Tour Guide",
    age: 41,
    location: "Narok",
    vibe: "Cultural Storytelling",
    quote:
      "a Maasai Mara game-drive circuit today gave us an incredible sighting. Moments like this never get old.",
    decisionStyle: "Deliberate, Independent",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Cultural fluency": 93, "Institutional trust": 59 },
    profile:
      "He values cultural storytelling, guest connection, and local revenue retention. Authentic, story-led pitches emphasizing community impact win him over, while sterile tourist scripts turn him off. He frequents Instagram, Facebook, WhatsApp, and Pinterest. He shows moderate price sensitivity, investing strategically in tools that support his independent tour business.",
  },
  {
    id: "yusuf-cheruiyot",
    name: "Yusuf Cheruiyot",
    segment: "Emerging Coastal Cultural Safari Guide",
    role: "Safari & Cultural Tour Guide",
    age: 26,
    location: "Narok, Kenya",
    vibe: "Emerging Coastal",
    quote:
      "a coastal cultural and history tour route today gave us an incredible sighting. Moments like this never get old.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Cultural fluency": 91, "Institutional trust": 55 },
    profile:
      "He values cultural exchange, wildlife immersion, and local community benefit. Engaging, community-centric proposals win him over, whereas exploitative corporate messaging turns him off. He uses Instagram, Facebook, WhatsApp, and Pinterest. He is price-sensitive, carefully balancing operational costs as he aims to build his own tour business.",
  },
  {
    id: "abdi-njoroge",
    name: "Abdi Njoroge",
    segment: "Scholarly Community Leader and Imam",
    role: "Imam & Community Leader",
    age: 58,
    location: "Eastleigh",
    vibe: "Scholarly Community",
    quote:
      "Friday sermon today focused on community responsibility. Grateful for a full, attentive congregation.",
    decisionStyle: "Deliberate, Consensus-seeking",
    platforms: ["WhatsApp", "Facebook", "Twitter / X"],
    traits: { "Scholarly rigour": 92, "Public accountability comfort": 58 },
    profile:
      "He values scholarly integrity, youth mentorship, and community welfare. Humble, respectful messaging grounded in accountability wins him over, while superficial or hasty proposals turn him off. He connects via WhatsApp, Facebook, LinkedIn, and Pinterest. Highly price-sensitive, he manages resources cautiously to maximize community benefit.",
  },
  {
    id: "maina-ndungu",
    name: "Maina Ndungu",
    segment: "Resourceful Gig Economy Delivery Rider",
    role: "Gig-Economy Delivery Rider",
    age: 27,
    location: "Kasarani",
    vibe: "Always in motion",
    quote:
      "food delivery for a ride-hailing app was steady today. Not a bad day, all things considered.",
    decisionStyle: "Spontaneous, Independent",
    platforms: ["WhatsApp", "TikTok", "Facebook", "Pinterest"],
    traits: { Adaptability: 85, Optimism: 75 },
    profile:
      "He values peer solidarity, reliable income, and asset ownership. Direct, honest messaging with clear financial benefits wins him over, while corporate buzzwords turn him off. He relies on WhatsApp, TikTok, Facebook, and Pinterest. Extremely price-sensitive, he constantly seeks ways to lower daily rental costs and maximize earnings.",
  },
];
